
# jobs:
#   build_deploy:
#     runs-on: ubuntu-18.04
#     steps:
#       - uses: actions/checkout@master
#       - name: Build
#         uses: TartanLlama/actions-eleventy@master
#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           publish_dir: _site 
#           publish_branch: gh-pages
#           github_token: ${{ secrets.GITHUB_TOKEN }}


name: Build Eleventy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build          

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}